### ISSUE TITLE
credhub regenerate doesn't honor the duration set in bosh-cli for existing certs

### ISSUE THREAD

**Issue by aad** [cloudfoundry-incubator/credhub#128]
What version of the credhub server you are using?
Server Version: 2.6.0

What version of the credhub cli you are using?
CLI Version: 2.5.2

If you were attempting to accomplish a task, what was it you were attempting to do?

i want to rotate cf certs managed by credhub, in the beginning, all certs have 1 year duration.
i have set the 5 years duration in cf-deployment using latest bosh-cli and have the changes deployed successfully.

What did you expect to happen?
i tried to use credhub-cli to regenerate the certs but the newly generated certs are still having 1 year duration.

What was the actual behavior?
i expect the newly generated certs have 5 years duration so that i don't need to rotate certs frequently.

Note: i have verified that if i delete the certs from credhub and deploy cf will generate 5 years certs. But we couldn't delete the certs in production, that's why i am finding a way to rotate certs and set larger duration in an existing environment.

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

If you are a PCF customer with an Operation Manager (PCF Ops Manager) please direct your questions to support (https://support.pivotal.io/)

**Comment by jknostman3** [comment]
@aad By default, BOSH does not regenerate certificates that already exist. It is running in no overwrite mode and so CredHub does not store the updated generation parameters. When the next generation happens it uses the parameters of the previous generation, such as the duration.

**Comment by aad** [comment]
sorry for replying on a closed issue.  Where are these parameters stored (database?)? Is there anyway to override them?
