### ISSUE TITLE
Importing a self-signed certificate not possible

### ISSUE THREAD

**Issue by dueckminor** [cloudfoundry-incubator/credhub#134]
What version of the credhub server you are using?
2.6.0

What version of the credhub cli you are using?
2.6.2

If you were attempting to accomplish a task, what was it you were attempting to do?
```
> credhub generate -n  /selfsigned/cert  --type=certificate --common-name="selfsigned"  --self-sign
> credhub export --path=/selfsigned | credhub import --file=/dev/stdin
Credential '/selfsigned/cert' at index 0 could not be set: The provided CA value is not a valid X509 certificate authority.

Import complete.
Successfully set: 0
Failed to set: 1
 - Credential '/selfsigned/cert' at index 0 could not be set: The provided CA value is not a valid X509 certificate authority.
One or more credentials failed to import.
```
What did you expect to happen?
I would expect, that I can import things I have created using the CredHub-CLI and that they look exactly the same afterwards (ignoring the changed id)

What was the actual behavior?
The self signed certificate can not be imported

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [X] I have included steps for reproduction

If you are a PCF customer with an Operation Manager (PCF Ops Manager) please direct your questions to support (https://support.pivotal.io/)

**Comment by bruce-ricard** [comment]
Note to whomever will fix this issue: when you think you are done, please add a test in our [import-export integration tests](https://github.com/cloudfoundry-incubator/credhub-acceptance-tests/blob/7a643ca064f9224b75ae25a341245a84c6e595ba/integration_test/import_export_test.go#L98-L101) to deal with self-signed leaves.

**Comment by HappyTobi** [comment]
Hi all,

The CredHub and CredHub acceptance test was done

CredHub PR: #150 
CredHub acceptance test PR: [#7](https://github.com/cloudfoundry-incubator/credhub-acceptance-tests/pull/7)

Kind regards

**Comment by jknostman3** [comment]
@HappyTobi & @damzog I am happy to report that we have made a new release of CredHub (2.9.0) that includes this fix. As a result, I will close out this issue.
