### ISSUE TITLE
https://credhub-api.cfapps.io/ is down

### ISSUE THREAD

**Issue by rkoster** [cloudfoundry-incubator/credhub#176]
It seems like the credhub API docs are down.
Could this be related to PWS being shut down?

**Comment by benjaminguttmann-avtq** [comment]
@rkoster According to the slack channel => CredHub API doc has a new URL: https://docs.cloudfoundry.org/api/credhub

**Comment by rkoster** [comment]
Thanks, the README apparently was also fixed: https://github.com/cloudfoundry-incubator/credhub/commit/efe8a2424526964d693afdedbfb3760deb9eba33
So this issue can be closed.
