### ISSUE TITLE
CredHub CLI "find" command should behave like the unix find command for filesystems

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry-incubator/credhub#2]
I have no way of discovering credentials saved under the root path `/`.  For example if I create an entry with no slashes in its name, I have to remember the name to get it back, since `find -a` and `find -p /` don't show them.  Or I think someone else on my team mucked around with my CredHub and I want to see if they left anything around, and it's hard to figure out.

In general, it appears that `find` shows "directories", not credentials, contrary to what a lot of the help text for the `find` command says.  Also, it refers to "directories" as "paths", which is confusing -- "paths" should refer to "directories" or entries.  In general I'd expect to be able to navigate the CredHub KV store similar to how I'd navigate a file system with the `find` utility, with recursive listing, options for showing only directories or only "end-values", limiting the depth to show, etc.

Additional information:

```
$ ./credhub --version
CLI Version: 0.3.0
CM Version: 0.3.0 build DEV
```

**Comment by pivotal-danjahner** [comment]
This issue was moved to cloudfoundry-incubator/credhub-cli#9
