### ISSUE TITLE
CredHub CLI "find -n ''" should find all credentials, not none

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry-incubator/credhub#3]
`./credhub find -n 'ab'` only finds creds where "ab" is a substring of the cred name.  So `./credhub find -n ''` should find creds that have the empty string as a substring of the name, which should be every single string.  Instead, this command returns nothing.

Assuming every credential has an alphabetical character in it, I can find all creds like this:

```
$ for x in {a..z}; do ./credhub find -n $x 2>/dev/null; done | grep 2016  | cut -f1 -d' ' | sort | uniq
DELETE_ME_AMIT
shell/pivotal/ssh_key
```

but that's not a desirable way to do it.

Additional info:

```
$ ./credhub --version
CLI Version: 0.3.0
CM Version: 0.3.0 build DEV
```

**Comment by pivotal-danjahner** [comment]
This issue was moved to cloudfoundry-incubator/credhub-cli#8
