### ISSUE TITLE
Limit for encrypted values in credhub? 

### ISSUE THREAD

**Issue by datenengel** [cloudfoundry-incubator/credhub#30]
We need to save string and json values securely in credhub (bosh release 1.6.5) for a special bosh deployment use case. 
For that we tested with different sizes of values and there was no problem to store strings/json with 233k bytes and more. 

But in the credhub source code on the persistence layer there is a limit of 7000 + 12 bytes set for all types of encrypted values. 

in the class EncryptedValue
```
 @Column(length = ENCRYPTED_BYTES + NONCE_SIZE, name = "encrypted_value", nullable = false)
 private byte[] encryptedValue;
```

with defined ENCRYPTED_BYTES = 7000 and NONCE_SIZE = 12 parameters. 

Fortunately  it seems that this limit is ignored, because the column length parameter applies only on string values and not byte arrays. 
From the javax.persistence.Column documentation (https://javaee.github.io/javaee-spec/javadocs/javax/persistence/Column.html): 
```
(Optional) The column length. (Applies only if a string-valued column is used.)
```

Before we can implement our special bosh deployment, we must ensure from credhub, that we are able to save values larger than the (for json and some other use cases too low) 7012 bytes limit. Therefor we have some questions: 

- What was the origin reason for implementing such a 7012 size limit? 
- Do you plan to fix this “bug”, so the limit will be enforced or will you just remove that limit ? 
- If you plan a limit, which size will it be ?

**Comment by jgf** [comment]
One suggestion would be to allow virtually unlimited sized values, but use path/prefix based quota.
For example: 
- all values in `/deployment1/*` in total can't exceed 2Gb, 
- all values in `/deployment2/*` in total can't exceed 10Gb
...

Then we could use acl based restrictions on who is allowed to push into which path (See https://github.com/cloudfoundry-incubator/credhub/issues/20) in order to prevent a single user to overload credhub.

**Comment by cppforlife** [comment]
i think it would really useful to support limiting of size based on optional policy (as @jgf shows) instead of individual items.

**Comment by athornton2012** [comment]
The team investigated this issue and found that the size of the json field is limited by the underlying database: https://www.pivotaltracker.com/story/show/157408875 Closing based on the findings.
