### ISSUE TITLE
Using Credhub behind Concourse, database growing?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/credhub#33]
What version of the credhub server you are using?

1.6.5 via https://github.com/starkandwayne/bucc/releases/tag/v0.4.1

What version of the credhub cli you are using?

1.6.0

If you were attempting to accomplish a task, what was it you were attempting to do?

Backup my BOSH + Credhub

```
bucc bbr backup
```

What did you expect to happen?

* I expected it to happen relatively quickly. I'm only use the credhub for < 100 items across my BOSH + Concourse.

What was the actual behavior?

It took 4 mins to backup credhub database:

```
[bbr] 2018/03/16 22:38:21 INFO - Backing up credhub on bosh/0...
[bbr] 2018/03/16 22:42:56 INFO - Finished backing up credhub on bosh/0.
```

The credhub backup is over 2G

```
-rw-rw-r-- 1 jumpbox jumpbox 2.3G Mar 16 22:46 bosh-0-credhub.tar
```

Is there an audit log or similar inside my database that's growing regularly because Concourse is polling it? Suggestions for operators to cleanup their DB to constrain its size?

**Comment by drnic** [comment]
My credhub BBR backup has grown to 3.1G now:
```
-rw-rw-r-- 1 jumpbox jumpbox 3.1G Apr  2 01:14 bosh-0-credhub.tar
```

**Comment by drnic** [comment]
Is the problem local to me or other people seeing it too?

**Comment by drnic** [comment]
Looks like PWS team is having issues with Credhub database growing too https://status.run.pivotal.io/incidents/y5jkw6xgv81t

**Comment by poblin-orange** [comment]
@drnic same here since we activated concourse-credhub. Guess the concourse credhub resolution is a bit excessive (each resource single get, for instance, when we use credhub to hold resource credentials)

**Comment by gberche-orange** [comment]
Seems related to story 154256575: [feature request: automate cleanup of database tables used in audit operations ](https://www.pivotaltracker.com/story/show/154256575) 

> It's fairly easy to fill these up as we've seen in the past.
> It would be a nicer operator experience if it didn't need to be done manually and in response to failure that over-full databases cause.
> 
> cited in Slack: https://pivotal.slack.com/archives/C133WF954/p1515686364000363

which mentions:

> Jan 31, 5:12 pm
> @cojackson
> respond to inform them that audit tables are going away entirely

**Comment by mdelillo** [comment]
@drnic @poblin-orange @gberche-orange It seems like you all figured this out by now. We had an issue where audit logs were quickly filling up our database.

In version 1.9+, the audit logs now go to a file instead. In versions 1.6 and 1.7, we added a property ([`audit_logs.days_retained`](https://github.com/cloudfoundry-incubator/credhub/blob/62925c5443341f91886fb3c40af8917383169ba6/src/main/resources/application-dev.yml#L8-L9)) that will only keep around logs from the last X days.
