### ISSUE TITLE
Feature request: bulk delete in a directory

### ISSUE THREAD

**Issue by ishustava** [cloudfoundry-incubator/credhub#34]
The Release Integration team is adding credhub support in [cf-deployment-concourse-tasks](https://github.com/cloudfoundry/cf-deployment-concourse-tasks). 

For fresh deploys we would like to ensure that there are no credentials stored in CredHub prior to deploy. For vars store, it was pretty simple: we just threw away the vars store file. 

To enable credhub, we have to do something like this:
```
for cred in `credhub f -j | jq -r .credentials[].name`; do credhub d -n $cred; done
```
Given 80+ credentials needed for `cf-deployment`, this is pretty slow and inconvenient. SOCKS5 proxy slows down connections even more.

We would love to have something like
```
credhub delete -p /my-bosh-director/cf
```
which will delete all credentials in a certain directory. 

What version of the credhub server you are using?
`v1.6.5`

What version of the credhub cli you are using?
`v1.7.0`

**Comment by athornton2012** [comment]
@ishustava seems like a good feature! Thanks for submitting. Will have @crawsible prioritize as necessary.

**Comment by scarytom** [comment]
out of interest @athornton2012, did this get prioritised?

**Comment by ankeesler** [comment]
Hey @scarytom - this story is on our radar. We would love to learn more about you use case, because we ran into this as well. What problem are you trying to solve with this feature?

**Comment by scarytom** [comment]
Thanks for responding @ankeesler 

I have a collection of credentials for which credhub is not the system of record.  These are held in a separate folder within credhub, and I update them using a script that takes new values from the upstream system of record.  I want that script to be able to wipe all the existing credentials in the relevant credhub folder before it loads the new ones, just in case any have been removed from the system of record.

At the moment I am using the for-loop workaround above, and it takes an age.

**Comment by ankeesler** [comment]
Thanks for responding @scarytom. This is really helpful to know your use case. You can follow along with the [story](https://www.pivotaltracker.com/story/show/156171089) for updates to this feature.

**Comment by scarytom** [comment]
@ankeesler That story link appears to be broken.  Is there any update on this issue?

**Comment by LizClaireMorris** [comment]
hi @scarytom the new story to track this can be found at: https://www.pivotaltracker.com/story/show/171446867. We'll be discussing it as a team soon.

**Comment by jknostman3** [comment]
I am closing this issue as this work was completed in the following story: https://www.pivotaltracker.com/story/show/171446867. Please let us know if that doesn't satisfy the issue here.
