### ISSUE TITLE
Need to replace compiled release tarball  package from ubuntu to  Centos.

### ISSUE THREAD

**Issue by wilfredwilly** [cloudfoundry-incubator/credhub#39]
Hi All,

Good Day :) 

Need to replace compiled release tarball  package from ubuntu to  Centos.

url: https://s3.amazonaws.com/bosh-compiled-release-tarballs/credhub-1.6.5-ubuntu-trusty-3541.10-20180329-193725-445975294-20180329193729.tgz?versionId=scvcFwaTcvkrpBoriVwjpomlFufz34Zh
    sha1: f56ec2497e39ea00acb0cd0bbe818ae285b9b44

Following error occurred during the compilation
===============================
Deploying:
  Running the pre-start script:
    Sending 'get_task' to the agent:
      Agent responded with error: Action Failed get_task: Task 626f2acc-1cd9-4095-7998-4c24b18a960c result: 1 of 5 pre-start scripts failed. Failed Jobs: uaa. Successful Jobs: postgres-9.4, director, user_add, credhub.

Exit code 1
 

Please let me know if there is any concerns.

**Comment by benmoss** [comment]
Hey @wilfredwilly, if you want to use Centos you shouldn't be using our precompiled releases. Just use the regular bosh release from http://bosh.io/releases/github.com/pivotal-cf/credhub-release?all=1
