### ISSUE TITLE
Question: Pushing credhub to CF as an app?

### ISSUE THREAD

**Issue by MatthiasWinzeler** [cloudfoundry-incubator/credhub#41]
Hi all

I'm thinking about pushing credhub to CF as an app. It looks like a regular spring boot application with a RDBMS backend, so it should run happily in CF...

Am I wrong? I noticed that there is no doc how to push it to CF (as opposed to UAA, where it's advertised very prominently) and Pivotal also only seems to ship it as a bosh release.
The README also explicitly states `This repository is for development and is not intended to be directly deployable`.

It looks like somehow it's not really supported to run it as an app. Is this true? Should credhub only be deployed as a bosh release?

**Comment by mdelillo** [comment]
@MatthiasWinzeler correct, we do not support pushing credhub as a CF app. The only deployment method we support is as a BOSH release.

**Comment by MatthiasWinzeler** [comment]
@mdelillo Thanks for getting back to me! Is there a specific reason you don't support it?

**Comment by mdelillo** [comment]
@MatthiasWinzeler as far as I know it was never a use case that anyone had needed or requested. It was designed to be deployed along with a BOSH director or as a BOSH release.

It may actually work as a CF app, I don't know anyone that has tried.

**Comment by MatthiasWinzeler** [comment]
@mdelillo thanks, got it! 
by the way, we deployed it and it works fine. of course it needs a tcp route if you want to use mTLS for authenticating the clients.
