### ISSUE TITLE
Document and refine the /health endpoint

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry-incubator/credhub#43]
I see that credhub is exposing a `/health` endpoint (which I could not yet find in the [API documentation](https://credhub-api.cfapps.io/)). This endpoint does not seem to check dependent resources health https://github.com/cloudfoundry-incubator/credhub/blob/c7aa6f0a51dbdc0ac48a5442b889adc9edb51db1/src/main/java/org/cloudfoundry/credhub/controller/v1/HealthController.java#L19

 It seems the history of spring [actuator code-like reuse](https://github.com/cloudfoundry-incubator/credhub/search?q=actuator&type=Commits) indeed included related datasource health check  https://github.com/cloudfoundry-incubator/credhub/commit/4702ca127749be9b6687b104ddc7cb6f1ea199ba

While external systems such as https://github.com/orange-cloudfoundry/credhub_exporter can monitor credhub health using [find-credentials](https://credhub-api.cfapps.io/#find-credentials) or [get-credentials](https://credhub-api.cfapps.io/#get-credentials) endpoint, the `/health` endpoint seems appealing (for performance and dependency coverage reasons).

I wonder whether direct usage of spring actuator was recently considered (as I could not find mention of it in the [credhub pivotal tracker](https://www.pivotaltracker.com/n/projects/1977341)), and may address potential (performance?) issues that occured in the past.

/CC @psycofdj psycofdj

---

> What version of the credhub server you are using?

2.0.2

**Comment by athornton2012** [comment]
@gberche-orange What do you mean by: 
> This endpoint does not seem to check dependent resources health

**Comment by gberche-orange** [comment]
@athornton2012 As an example, I mean that the `/health` endpoint does not check that the underlying resources such as the credhub store or configured HSM is also available. In other words, it may respond `UP` while all credhub requests may fail

**Comment by athornton2012** [comment]
@gberche-orange makes sense, perhaps it would be worthwhile for us to improve our /health endpoint. @crawsible any thoughts/hesitations?

**Comment by crawsible** [comment]
I'm open to being convinced otherwise but it doesn't seem obvious to me that our health endpoint should be doing anything more than reporting on the proper functioning of the server itself. The health endpoint primarily exists for BOSH and the post-start script. My expectation is that UAA, a dependent DB, an HSM etc. are also being monitored if they're important responsibilities.

As I said I'm open to being convinced otherwise though. Could you tell me more about your use-case, and in particular what value this would bring you over and above simply monitoring the dependent services as well?

**Comment by athornton2012** [comment]
@gberche-orange bumping on this

**Comment by gberche-orange** [comment]
@crawsible @athornton2012

Sorry for late follow up. While the dependent services would indeed be monitored separated, it seems important to me to have credhub report failures when network partitions prevents credhub to access to UAA/DB/HSM, which results in credhub being unable to provide its service. 

Springboot actuator automates this practice for various dependent resources, see https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#_auto_configured_healthindicators

**Comment by ankeesler** [comment]
@gberche-orange - we recently updated the `/health` endpoint in CredHub as a part of this story: https://www.pivotaltracker.com/story/show/158726819. CredHub now uses Boot healthcheck functionality. Is this the same functionality that you are referencing? If so, does it resolve your ask here? Thank you!

**Comment by gberche-orange** [comment]
thanks @ankeesler 

I can now see the `/health` endpoint being documented at http://credhub-api.cfapps.io/version/2.1/#health although response body does not seem described. Might be worth adding a link to https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#_writing_custom_healthindicators ![image](https://user-images.githubusercontent.com/4748380/53886376-2d05d980-4020-11e9-8ae5-3dd640cd5789.png)  or https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/actuate/health/Status.html


Besides, I believe the health endpoint would benefit from reporting as down when it is unable to access its UAA/DB/HSM. 

I could not see this being described in the story acceptance criteria.

I would assume that spring boot default health indicator would be enabled by default
https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#_auto_configured_healthindicators

including the `DataSourceHealthIndicator` that would test access to the credhub db by default.

It might make sense to add a `uaa health indicator` to test connectivity to the uaa server.

**Comment by martys34** [comment]
@gberche-orange There are other ways to check the health of UAA/DB/HSM, like hitting the UAA health endpoint, attempting to store something in the DB, and attempting to encrypt something with the HSM. That would be a lot of work to check the health of CredHub but this feature request doesn't seem like a top priority for our team at the moment. We are going to close this issue but will reopen if we receive similar requests.
