### ISSUE TITLE
Feature request: support meta-data associated to credhub objects

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry-incubator/credhub#45]
As usage of credhub expands and becomes a source of truth for operators configuration, it becomes useful to be able to attach additional meta-data to credhub entries in the [set-credentials endpoint](https://credhub-api.cfapps.io/#set-credentials) similar to the [bosh job specs (metadata)](https://bosh.io/docs/jobs/#spec), e.g.
* a `description` field 
* an `example` field
* a JSON schema field that would apply to the `Value`or `Json` types (similarly as how json schemas are used by the [OpenServiceBroker api](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#input-parameters-schema-object) by service authors to hint users about expected parameters format)

The meta-datas would help operators that might need to rotate or update credhub entries about the possible side effects of such updates, additional constraints/requirements expected on the values.

The meta-datas might not necessary be considered as sensitive data, and might be subject to cost optimization related to which storage to use (e.g. avoid storing them in HSM if this can be expensive)

This would also enable to tooling authors to provide credhub UIs.

---

What version of the credhub server you are using?
2.0.2

**Comment by athornton2012** [comment]
@gberche-orange The JSON credential type lets you store metadata about the credential and also encrypts that metadata. There is a track of work that we have prioritized to store the expiration date of certificates. As far as other metadata goes, the JSON credential type should suffice. Closing.

**Comment by gberche-orange** [comment]
@athornton2012 while for the `Type: JSON ` adding user-defined meta-data as additional json entries is an acceptable workaround, it does not seem possible for the other types of entries such as `Type: Value`, `Type: Password`, `Type: Certificate`, `Type: User`, `Type: RSA`, `Type: SSH`

Example of user defined meta-data that would be added to such types of entries:
* `documentation` stating the:
   * expected usage of the entry, possibly deprecation notice
   * expected procedure to use when setting the entry (e.g. cypher to use, additional password strength) when not using credhub to generate these entries
* `json-schema` that eases input validation of entries with `Type: Value` or `Type: Json` (similarly as how json schemas are used by the OpenServiceBroker api by service authors to hint users about expected parameters format)

**Comment by crawsible** [comment]
@gberche-orange Just to clarify, you're talking about enabling users to include arbitrary data alongside a credential record, analogous to Kubernetes' [labels and selectors](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/)? Could you go into a little more detail about how you're using CredHub today and how this would help you?

**Comment by gberche-orange** [comment]
@crawsible 

> you're talking about enabling users to include arbitrary data alongside a credential record, analogous to Kubernetes' labels and selectors

Partly. K8S labels are too restrictive in size and [accepted character sets](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set) to support the documentation input validation use-case I mentioned in https://github.com/cloudfoundry-incubator/credhub/issues/45#issuecomment-425998528

> Could you go into a little more detail about how you're using CredHub today and how this would help you?

We're using credhub not only to store sensititve values, but also to configure configuration params that are shared across bosh deployments. In other words, we're using credhub as a configuration server (leveraging bosh director ability to interpolate these entries in bosh deployment manifests)

Being able to attach metadata to credhub entries would enable users that need to provision these configuration entries to be displayed documentation and possibly input validation for these configurations.

So 1st class support for the following metadata would be better matching my use-case than K8S style labels:
* a 'documention' metadata applicable to `Type: Value`, `Type: Password`, `Type: Certificate`, `Type: User`, `Type: RSA`, `Type: SSH` 
*  a 'json-schema' metadata appliceable to `Type: Value` or `Type: Json`

**Comment by jknostman3** [comment]
Hey @gberche-orange,

The work for this has been accepted and is scheduled to be released in the coming weeks. Be on the lookout for CredHub 2.6.0.

Closing this issue out.

**Comment by gberche-orange** [comment]
thanks @jknostman3 ! 

The current documentation does not yet detail size limit of the Json object, input validation performed (allow nested object), or where the metadata is attached (version vs credential)
https://credhub-api.cfapps.io/version/develop/#_generate_a_certificate_credential

> Path | Type | Required | Description
> -- | -- | -- | --
> name | String | true | The name of the credential.
> [...]
> metadata | Object | false | Additional metadata of the credential.
> 

Whereas the pivotal tracker story at https://www.pivotaltracker.com/n/projects/1977341/stories/160931048 seems to have some related intents 

> think about size limits
> input validation (just json serializable or more validation)
> metadata is added to credential version (not the credential) object as any json serializable thing (JsonNode)
> 

Any chance to refine the documentation before 2.6.0 gets released ?

Other than that, it looks great on the [api doc preview](https://credhub-api.cfapps.io/version/develop/#_set_a_json_credential)

> Set a credential with a description
>
> $ curl 'https://example.com/api/v1/data' -i -X PUT \
>     -H 'Content-Type: application/json' \
>     -H 'Authorization: Bearer [some-token]' \
>     -d '{
>   "name": "/some-value-name",
>   "type": "json",
>   "metadata": { "description": "example metadata"},
>   "value": {
>     "some-json-key": "some-json-value"
>   }
> }'

>Find a Credential by ID (Type: Value)
>
> $ curl 'https://example.com/api/v1/data/8ccd2d49-1652-419a-8e26-203a73e21f77' -i -X GET \
>     -H 'Content-Type: application/json' \
>     -H 'Authorization: Bearer [some-token]'
> HTTP/1.1 200 OK
> Content-Type: application/json;charset=UTF-8
> Content-Length: 238
> 
> {
>   "type" : "value",
>   "version_created_at" : "2019-02-01T20:37:52Z",
>   "id" : "8ccd2d49-1652-419a-8e26-203a73e21f77",
>   "name" : "/some-value-path",
>   "metadata" : {
>     "description" : "example metadata"
>   },
>   "value" : "some-value"
> }
>
