### ISSUE TITLE
Feature Request: return principal that created a credentials in get-credentials endpoint

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry-incubator/credhub#46]
As a credhub user, in order to clean up credhub entries following a bosh deployment deletion, I need to distinguish credhub entries that I (or my bosh-director) created from credhub entries other users created.

Currently the [get-credentials endpoint](https://credhub-api.cfapps.io/#get-credentials) only returns 
```json
{
  "id": "2993f622-cb1e-4e00-a267-4b23c273bf3d",
  "name": "/example-password",
  "type": "password",
  "value": "6mRPZB3bAfb8lRpacnXsHfDhlPqFcjH2h9YDvLpL",
  "version_created_at": "2017-01-05T01:01:01Z"
}
```

Additionally, the audit traces seem hard to access to credhub users (accessible in audit logs or credhub db) and targetted towards credhub admins or SIEM tools.

It would be useful to have  [get-credentials endpoint](https://credhub-api.cfapps.io/#get-credentials)  return additional field(s) describing the user/principal that generated the secret, inspired by the [identity scheme](https://github.com/cloudfoundry-incubator/credhub/blob/master/docs/authentication-identities.md#identity-scheme)

```json
{
  "id": "2993f622-cb1e-4e00-a267-4b23c273bf3d",
  "name": "/example-password",
  "type": "password",
  "value": "6mRPZB3bAfb8lRpacnXsHfDhlPqFcjH2h9YDvLpL",
  "version_created_at": "2017-01-05T01:01:01Z",
  "created_by": {
      "auth_type": "uaa-user",
      "scope":"zone1",
      "primary_identifier": "1234" 
   }
}
```

Possibly additional fields available in the AuditRecord might be useful to include, such as username
https://github.com/cloudfoundry-incubator/credhub/blob/fc8bd65383e985bf1bdd271b4964a1449db58078/src/main/java/org/cloudfoundry/credhub/audit/CEFAuditRecord.java#L44

--------
What version of the credhub server you are using?
 
2.0.2

**Comment by athornton2012** [comment]
@gberche-orange  My hunch is that permissions of CredHub users should not be exposed to non-admin users (users that do not have read-acl permissions). That is the state of credhub currently. There is also no concept of an owner of a credential in credhub. The audit log is the source of truth on this. Closing.

**Comment by gberche-orange** [comment]
thanks @athornton2012  for the follow up. 

> There is also no concept of an owner of a credential in credhub.

This issue is actually suggesting to introduce such concept in order to make it programmatically accessible (which the audit log makes hard AFAIK)

It would be fine to conditionally return the ower of a credential depending on the permissions of the caller in order to protect owner data.

**Comment by johnpfield** [comment]
@gberche-orange With respect to the cleanup use case, don't the existing ACLs provide this scoping implicitly?  I would think you can't see or delete (either accidentally, or intentionally) any credentials for which you don't have the appropriate ACL access.   

> There is also no concept of an owner of a credential in credhub.

@athornton2012 Given that constraint, how do we determine how to construct and maintain the corresponding ACL entries?  Are all the ACL entries managed by a (unitary) admin user?

**Comment by crawsible** [comment]
@johnpfield In the old days (CredHub 1.x), CredHub would create ACEs for all supported operations at the time of credential creation, granting the identity created the credential full permissions to the credential they'd just created. Those ACEs could be deleted like any other; and it was certainly possible to orphan credentials in the system. All identities were permitted to create new credentials.

As of CredHub 2.0, access can be provisioned to namespaces as well as to specific named credentials, and ACEs can be defined in CredHub's manifest properties, so there's no need to create a bunch of ACEs when a new credential is created. Authenticated identities no longer have the implicit right to create new credentials. Instead, operators can define their own local or global admins and users as they deem fit.

**Comment by gberche-orange** [comment]
@johnpfield 

> With respect to the cleanup use case, don't the existing ACLs provide this scoping implicitly? I would think you can't see or delete (either accidentally, or intentionally) any credentials for which you don't have the appropriate ACL access.

In cleanup use-case (detailed in https://github.com/cloudfoundry/bosh/issues/2045 and https://github.com/cloudfoundry/bosh/issues/2047), the requirement  is to be able clean up credentials entries created by the bosh-director principal within /bosh-director/bosh-deployment/*` path, but not credentials created by other principals (say "guillaume" a human using credhub cli).

Both the bosh director and "guillaume" users would have the `write`and `delete` [permissions](https://github.com/cloudfoundry-incubator/credhub/blob/master/docs/authorization-phase1.md#supported-operations) to the `/bosh-director/bosh-deployment/*` path.
