### ISSUE TITLE
Error while importing credentials coming from an export

### ISSUE THREAD

**Issue by shoudusse** [cloudfoundry-incubator/credhub#47]
What version of the credhub server you are using?
Version 2.0.2

What version of the credhub cli you are using?
Version 2.0.0

If you were attempting to accomplish a task, what was it you were attempting to do?
I want to import credentials coming from a `credhub export` command

What did you expect to happen?
I expected my crendentials to be imported without error.

What was the actual behavior?
Some credentials could not be imported

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

If you try to export / import datas (even from / to the same credhub) you will have an error for all `ssh` and `user` type credentials.
You can reproduce theussue with these commands:
```
$ credhub set -t user -n john_user -z john -w john-secret
id: 484e340d-fe04-4541-a398-89ef2eeb0236
name: /john_user
type: user
value: <redacted>
version_created_at: "2018-09-21T13:52:20Z"

$ credhub export -f /tmp/credhub-export.yml
$ credhub import -f /tmp/credhub-export.yml
Credential '/john_user' at index 0 could not be set: The request includes an unrecognized parameter 'password_hash'. Please update or remove this parameter and retry your request.

Import complete.
Successfully set: 0
Failed to set: 1
 - Credential '/john_user' at index 0 could not be set: The request includes an unrecognized parameter 'password_hash'. Please update or remove this parameter and retry your request.
```
The error concerns fields that can be automaticaly retrieved.
- `public_key_fingerprint` for `ssh` type
- `password_hash` for `user` type

**Comment by crawsible** [comment]
@shoudusse Thanks for reporting. I think it's fine for the credhub CLI to ignore certain values in import files that are likely to have been generated by an export statement. I broadly think it makes sense for the CLI to refuse to import items with unknown keys, but ignoring specifically `public_key_fingerprint` for `ssh` type credentials, and `password_hash` for `user` type credentials, seems sensible. Does that make sense to you or were you expecting some other sort of behavior?

**Comment by shoudusse** [comment]
Hello @crawsible ,
I think ignoring  specifically `public_key_fingerprint` for `ssh` type credentials, and `password_hash` for `user` type credentials is the behavior I was expecting.
Thanks for your help

**Comment by athornton2012** [comment]
@shoudusse we will prioritize this issue as necessary. You can follow along with the tracker story listed above.
