### ISSUE TITLE
Credhub Deployment Failure - Encryption Provider

### ISSUE THREAD

**Issue by benjoyce** [cloudfoundry-incubator/credhub#48]
I'm getting an error trying to deploy Credhub alongside the Director:
From: `/var/vcap/sys/log/credhub/credhub.log`
```
Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2018-10-10T20:56:29.797Z [main] .... ERROR --- SpringApplication: Application startup failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'encryptedValueDataService' defined in URL [jar:file:/var/vcap/data/packages/credhub/13a554b2cb4fbf2bfd25326f7dbb11da156a2e50/credhub.jar!/BOOT-INF/classes!/io/pivotal/security/data/EncryptedValueDataService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'encryptionKeyCanaryMapper' defined in URL [jar:file:/var/vcap/data/packages/credhub/13a554b2cb4fbf2bfd25326f7dbb11da156a2e50/credhub.jar!/BOOT-INF/classes!/io/pivotal/security/service/EncryptionKeyCanaryMapper.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.pivotal.security.service.EncryptionKeyCanaryMapper]: Constructor threw exception; nested exception is java.lang.RuntimeException: java.lang.NullPointerException
```

Checked the docs: https://github.com/pivotal-cf/credhub-release/blob/master/docs/troubleshooting-guide.md

_[Post-start error] org.cloudfoundry.credhub.service.EncryptionKeyCanaryMapper required a bean of type 'org.cloudfoundry.credhub.service.EncryptionService' that could not be found
This failure indicates that the active encryption provider type has not be defined or is an invalid value. Check the encryption.providers.type value in your manifest._

Here's my manifest (snippet) - taken from the `credhub.yml` ops file:
```
    encryption:
     providers:
     - name: internal
      type: internal
     keys:
     - provider_name: internal
      key_properties:
       encryption_password: ((credhub_encryption_password))
      active: true
```

I'v checked `creds.yml` and there is a value present for `credhub_encryption_password`.

I have another Director+USA+Credhub working fine using the same release versions and manifests, the only difference being the working deployment is done from an Ubuntu 16 vm, and the failing from a RHEL7 vm.

Any ideas?

**Comment by chhhavi** [comment]
Resolved in Slack. Closing. Please reopen if need be.
