### ISSUE TITLE
Don't see PivotalTracker links when opening up issues

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry-incubator/credhub#5]
When I open this issue, I'd expect an automatic link to a Pivotal Tracker story copying this issue to a story in the CredHub icebox.  Makes it harder to know if issues opened here will be tracked by anyone.  Looks like that's not setup.

/cc @pivotal-danjahner @ishustava

**Comment by pivotal-danjahner** [comment]
This has been configured.
