### ISSUE TITLE
Deploy credhub inside a kubernetes cluster

### ISSUE THREAD

**Issue by luismoramedina** [cloudfoundry-incubator/credhub#50]
Hi,

I am looking for some documentation about installing/deploying a CredHub instance inside a kubernetes/openshift cluster. Is it possible? Or is only available in cloud foundry platforms?

Thanks and regards.

**Comment by chhhavi** [comment]
Hi @luismoramedina This is not officially supported but I believe someone at SpringOne gave a talk about trying to do this. [Here](https://www.youtube.com/watch?v=uevyVtnPOwI) is a link to the talk. Closing
