### ISSUE TITLE
Unable to gain valid mTLS client certs

### ISSUE THREAD

**Issue by tyrannosaurus-becks** [cloudfoundry-incubator/credhub#53]
**What version of the credhub server you are using?**
Master, at commit 6eb9d8cbcda44744762e4760d02ac960bd0b6645

**What version of the credhub cli you are using?**
2.2.0

**If you were attempting to accomplish a task, what was it you were attempting to do?**
I was attempting to test [the new mTLS client in the go-credhub repo](https://github.com/cloudfoundry-community/go-credhub/pull/9/files) by running CredHub locally and using its test certificates.

**What did you expect to happen?**
I was expecting to be able to test CredHub's mTLS auth with client certs.

**What was the actual behavior?**

I may be going about this test incorrectly. Here's what I was doing. I started CredHub locally using:
```
$ ./scripts/start_server.sh -Dspring.profiles.active=dev,dev-h2,dev-local-uaa
```
I attempted to use the linked client using various combinations of the certs generated in `src/test/resources`, such as `client_ca_cert.pem` and `client_ca_private.pem`, and `server_ca_cert.pem` and `server_ca_private.pem`. None worked. I noticed that perhaps I needed separate client certs that would be generated by running acceptance tests, as per the README:

>Assuming it works, that will generate some test client certificates for testing mutual TLS (in `certs/` in the acceptance test directory) and run the acceptance test suite against your locally running credhub server.

However, after attempting to run those tests using:
```
$ CREDENTIAL_ROOT=/home/tbex/go/src/github.com/cloudfoundry-incubator/credhub/src/test/resources UAA_CA=/home/tbex/go/src/github.com/cloudfoundry-incubator/credhub/src/test/resources/ca/dev_uaa.pem ./scripts/run_tests.sh
```
... the mTLS tests succeed, but the smoke tests fail with:
```
• Failure in Spec Teardown (AfterEach) [0.075 seconds]
UAA Lifecycle [AfterEach] lifecycle 
/home/tbex/go/src/github.com/cloudfoundry-incubator/credhub-acceptance-tests/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:365

  Expected error:
      <*errors.errorString | 0xc0005b4590>: {
          s: "Received HTTP 403 error while revoking token from auth server: \"{\\\"error\\\":\\\"insufficient_scope\\\",\\\"error_description\\\":\\\"Insufficient scope for this resource\\\",\\\"scope\\\":\\\"uaa.admin tokens.revoke\\\"}\"",
      }
      Received HTTP 403 error while revoking token from auth server: "{\"error\":\"insufficient_scope\",\"error_description\":\"Insufficient scope for this resource\",\"scope\":\"uaa.admin tokens.revoke\"}"
  not to have occurred

  /home/tbex/go/src/github.com/cloudfoundry-incubator/credhub-acceptance-tests/api_client_test/uaa_lifecycle_test.go:15
------------------------------
•••••••••

Summarizing 1 Failure:

[Fail] UAA Lifecycle [AfterEach] lifecycle 
/home/tbex/go/src/github.com/cloudfoundry-incubator/credhub-acceptance-tests/api_client_test/uaa_lifecycle_test.go:15

Ran 18 of 18 Specs in 1.497 seconds
FAIL! -- 17 Passed | 1 Failed | 0 Pending | 0 Skipped
```
And there is no resulting `certs/` directory yielding test certs.

**Comment by martys34** [comment]
@tyrannosaurus-becks It seems like this is a problem with your local development UAA. The error message implies that your UAA admin doesn't have the proper scopes. it seems like the UAA admin client was not granted `uaa.admin` authority. There could be a number of reasons this happened: perhaps you are using an old version of UAA, or maybe you overwrote this in you manifest.
