### ISSUE TITLE
Don't print out credentials on `credhub import`

### ISSUE THREAD

**Issue by wfernandes** [cloudfoundry-incubator/credhub#54]
What version of the credhub server you are using?
Server Version: 0.0.0

What version of the credhub cli you are using?
CLI Version: 1.7.5

If you were attempting to accomplish a task, what was it you were attempting to do?
`credhub import --file <some-file>`

What did you expect to happen?
Credhub to say successfully import credentials **without printing the credentials to stdout**. That is, I expect just the following output.
```
Import complete.
Successfully set: 3
Failed to set: 0
```
We are running this command in CI and I didn't expect the CLI to print out all our credentials to concourse web output.

What was the actual behavior?
The current behavior prints out all the credentials to stdout. 
http://credhub-api.cfapps.io/version/2.1/#bulk-import
```
id: 67fc3def-bbfb-4953-83f8-4ab0682ad675
name: /example-ssh
type: ssh
value:
  public_key: ssh-rsa AAAAB3NzaC1y...W9RWFM1
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    ...
    -----END RSA PRIVATE KEY-----
version_created_at: 2017-01-01T04:07:18Z

id: 2ba73fbd-439e-40ef-b005-0e1db8815063
name: /example-password
type: password
value: SqFcE2c0AuRvet2YhrxdFbPtkBmjiq
version_created_at: 2017-01-01T04:07:28Z

id: 22a1e87b-ba0b-4bc9-bb26-4e5fc5fb1b2f
name: /example-value
type: value
value: sample
version_created_at: 2017-01-01T04:07:38Z

Import complete.
Successfully set: 3
Failed to set: 0
```

Please confirm where necessary:
* [x] I have included a log output
* [ ] My log includes an error message
* [x] I have included steps for reproduction

If you are a PCF customer with an Operation Manager (PCF Ops Manager) please direct your questions to support (https://support.pivotal.io/)

**Comment by martys34** [comment]
@wfernandes Thanks for pointing this out. We'll prioritize this as necessary

**Comment by ankeesler** [comment]
@wfernandes thanks again for filing this issue. We have released a fix here: https://github.com/cloudfoundry-incubator/credhub-cli/releases/tag/2.5.0.

Please let us know if you run into anymore issues.
