### ISSUE TITLE
unsupported protocol scheme \"\"

### ISSUE THREAD

**Issue by sppsun** [cloudfoundry-incubator/credhub#58]
Hi, guys, recently I tried to deploy cfcr env on mac, but met lots problems. Such as, when executed "credhub api --server=https://192.168.50.6:8443 --ca-cert=./cert" command would throw an error message "Get /info: unsupported protocol scheme \"\"". Very weird.  Please help me double check why? Thank you very much.

**Comment by martys34** [comment]
Hi @sppsun. It looks like you've got the port for the server wrong. CredHub listens on port 8844; 8443 is UAA.

Hope that helps!
