### ISSUE TITLE
"credhub generate --no-overwrite" overwrites passwords set with "credhub set"

### ISSUE THREAD

**Issue by richardTowers** [cloudfoundry-incubator/credhub#60]
## What version of the credhub server / cli are you using?

```
bash-4.4# credhub --version
CLI Version: 2.5.3
Server Version: 2.5.6
```

## If you were attempting to accomplish a task, what was it you were attempting to do?

Using `credhub generate` with the `--no-overwrite` flag to generate a new value for a password if and only if it does not already have a value.

Consider:

```
bash-4.4# credhub set -n "/path" -t password -w "test-test-test"
id: dbaee067-812a-446c-81a8-cc86cd447d46
name: /path
type: password
value: <redacted>
version_created_at: "2019-10-28T14:04:59Z"

bash-4.4# credhub get -n "/path"
id: dbaee067-812a-446c-81a8-cc86cd447d46
name: /path
type: password
value: test-test-test
version_created_at: "2019-10-28T14:04:59Z"

bash-4.4# credhub generate -n "/path" -t password --no-overwrite
id: af96f43d-625b-4ef8-acc8-467c917b55ab
name: /path
type: password
value: <redacted>
version_created_at: "2019-10-28T14:06:19Z"

bash-4.4# credhub get -n "/path"
id: af96f43d-625b-4ef8-acc8-467c917b55ab
name: /path
type: password
value: PWlybYx60cSMD3kTHFYTnHClAymcJD
version_created_at: "2019-10-28T14:06:19Z"
```

## What did you expect to happen?

The password should be left with its value from the original `credhub set` and not overwritten.

## What was the actual behavior?

The password was overwritten

Please confirm where necessary:
* [x] I have included a log output
* [ ] My log includes an error message
* [x] I have included steps for reproduction

**Comment by ankeesler** [comment]
@richardTowers - thank you for opening this issue. We have fixed this behavior. Our [2.5.9](https://github.com/pivotal/credhub-release/releases/tag/2.5.9) release of CredHub should contain this fix. Please let us know if this does not fix your issue. Thanks!

**Comment by richardTowers** [comment]
Thanks folks! 

I'll try to remember to test this when we upgrade and let you know how it goes.
