### ISSUE TITLE
Feature Request: DER certificates.

### ISSUE THREAD

**Issue by mxplusb** [cloudfoundry-incubator/credhub#63]
What version of the credhub server you are using?

```sh
$ credhub --version
CLI Version: 2.5.2
Server Version: 2.5.7
```

What version of the credhub cli you are using?

```
$ credhub --version
CLI Version: 2.5.2
Server Version: 2.5.7
```

If you were attempting to accomplish a task, what was it you were attempting to do?

Create a new DER-formatted certificate. It would be nice if there was an option for using DER-formatted certificates as part of the certificate generation process. SAML 2.0 requires DER-formatted certificates, so these certificates cannot be generated or managed by Credhub as Credhub only supports PEM-formatted certificates.

**Comment by ankeesler** [comment]
@mxplusb - we would like to maintain a single x509 encoding format in our server for engineering simplicity. There is an argument that could be made to do in the CredHub CLI. At this time, we will not be prioritizing this feature, but please feel free to open a PR in the CLI if you wish to move forward with this feature. In the meantime, if you aren't already, we recommend using `openssl` to convert from DER to PEM.
