### ISSUE TITLE
Actor must not be null when using authorization_code grant type

### ISSUE THREAD

**Issue by sneal** [cloudfoundry-incubator/credhub#66]
What version of the credhub server you are using?
2.5.7

What version of the credhub cli you are using?
2.5.3

If you were attempting to accomplish a task, what was it you were attempting to do?
Credhub integrated into UAA (w/SAML) using a web app to read/write to credhub with ACLs set on various paths. The web app is  using a UAA client with `authorization_code` grant type.

What did you expect to happen?
Data to be returned

What was the actual behavior?
No data. "IllegalStateException: actor must not be null" in the credhub log

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

If you are a PCF customer with an Operation Manager (PCF Ops Manager) please direct your questions to support (https://support.pivotal.io/) 

This method is returning null, because it looks like it doesn't support the `authorization_code` grant type:
https://github.com/cloudfoundry-incubator/credhub/blob/87befb1dc9f6b7ddffa7ce6568ef04e21de3466d/components/auth/src/main/java/org/cloudfoundry/credhub/auth/UserContext.java#L107

**Comment by ankeesler** [comment]
Our gut feeling is that this is something that just fell through the cracks. I think this just might not have been a requirement at the time that CredHub was getting rolled out. We will do some more archeology on this, but seems like something we can add.

**Comment by ankeesler** [comment]
Did you run into this when building your CredHub web app?

**Comment by bruce-ricard** [comment]
@ankeesler It seems to us that the "authorization code" OAuth grant type is not supported by the Credhub server. I can think of 2 action items for us at this point:

1. Fix this code path by returning an actual error when a user tries to use the "auth code" grant type, by saying something like "Error: the authorization code grant flow is not supported", instead of apparently returning nothing.
2. Updating the docs to indicate that it's not supported (if they are not already)

**Comment by jknostman3** [comment]
@sneal We are trying to get a better gauge of this issue in order to prioritize the story that was created. Would you be able to explain your use case a little more specifically?

**Comment by sneal** [comment]
@jknostman3 I was attempting to get a Credhub web based admin tool working with individual user accounts in UAA (SAML origin). It unfortunately ended up only worked with a client. I'd like to see the error message cleaned up, it might save someone from having to dive into the code in the future.

We ended up giving granular access via the Credhub CLI which was workable. The annoying part was having to grant each individual developer access to specific folders in Credhub which required us to use UAAC to find every developers UAA id. Assigning groups would be nice here.

**Comment by jknostman3** [comment]
@sneal  Thanks for the details on your use case. We updated the bug in the backlog to be more focused on a clearer error message. We will let you know when this has been implemented.

**Comment by jknostman3** [comment]
Closing this issue out since the Error message was improved and has shipped.
